/**
 * build-icons — generates React icon components from `assets/svg/icons/`.
 *
 * Pipeline:
 *   1. Walk `assets/svg/icons/{18,24,32}` for `*.svg`.
 *   2. Group by canonical kebab-case name across sizes.
 *   3. For each name, extract the SVG inner content per size, normalize
 *      colors (`#454C53` → `currentColor`; semantic colors like `#F95C5C`
 *      are preserved so the error icon stays red regardless of `color`).
 *   4. Emit one `.tsx` per icon using `dangerouslySetInnerHTML` — avoids
 *      the SVG → JSX attribute conversion mess and keeps fidelity with
 *      complex Figma exports (masks / groups / multiple paths).
 *   5. Emit `index.ts` re-exporting every icon as `<Name>Icon`.
 *   6. Emit a manifest `MANIFEST.json` consumers / docs can read.
 *
 * Run:
 *   pnpm --filter @polaris/ui build:icons
 *
 * Output: `packages/ui/src/icons/`. Files in this directory are
 * auto-generated and gitignored — do NOT edit by hand. Updating an
 * icon = drop the new SVG into `assets/svg/icons/{size}/`, run
 * `pnpm normalize:icons` (if from Figma export), then `build:icons`.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ASSET_ROOT = resolve(__dirname, '../../../assets/svg/icons');
const OUT_ROOT = resolve(__dirname, '../src/icons');

type Size = 18 | 24 | 32;
const SIZES: Size[] = [18, 24, 32];

interface IconEntry {
  /** kebab-case slug from filename. */
  slug: string;
  /** PascalCase component identifier (no `Icon` suffix yet). */
  pascal: string;
  /** Component export name — `<pascal>Icon`. */
  componentName: string;
  /** SVG inner content per size (string between `<svg>` and `</svg>`). */
  inner: Partial<Record<Size, string>>;
  /** Default size — first available in [24, 18, 32] preference order. */
  defaultSize: Size;
}

function pascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** Strip the wrapping `<svg ...>` and `</svg>` tags, return the inner
 *  content. Also normalizes color attributes. */
function extractInner(svg: string): string {
  // Match the opening <svg ...> tag and closing </svg>.
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error('SVG missing root <svg> tag');
  let inner = m[1].trim();

  // Color normalization. `#454C53` is the design-team default stroke
  // for monochrome icons — turn it into `currentColor` so the icon
  // inherits the consumer's text color (Tailwind `text-{token}` etc).
  // Other hex values (notably `#F95C5C` for the error icon) are kept
  // as-is so semantic colors stay baked in.
  inner = inner.replace(/(stroke|fill)="#454C53"/gi, '$1="currentColor"');

  return inner;
}

function buildEntry(slug: string): IconEntry {
  const inner: Partial<Record<Size, string>> = {};
  for (const size of SIZES) {
    const file = join(ASSET_ROOT, String(size), `${slug}.svg`);
    let stat;
    try {
      stat = statSync(file);
    } catch {
      continue;
    }
    if (!stat.isFile()) continue;
    inner[size] = extractInner(readFileSync(file, 'utf8'));
  }
  // Prefer 24 (the design system's default) → fallback 18 → 32.
  const defaultSize: Size =
    inner[24] !== undefined ? 24 : inner[18] !== undefined ? 18 : 32;
  const pascal = pascalCase(slug);
  return {
    slug,
    pascal,
    componentName: `${pascal}Icon`,
    inner,
    defaultSize,
  };
}

function emitIconComponent(entry: IconEntry): string {
  const sizes = SIZES.filter((s) => entry.inner[s] !== undefined);
  // Build the INNER constant. Stringify-escape backticks and backslashes;
  // Figma export shouldn't contain either, but be safe.
  const innerEntries = sizes
    .map((s) => {
      const escaped = entry.inner[s]!.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
      return `  ${s}: \`${escaped}\``;
    })
    .join(',\n');

  const sizeUnion = sizes.join(' | ');

  return `// AUTO-GENERATED by packages/ui/scripts/build-icons.ts — do not edit by hand.
// Source: assets/svg/icons/{${sizes.join(',')}}/${entry.slug}.svg
import { forwardRef } from 'react';
import type { PolarisIconProps } from './types';

type Size = ${sizeUnion};

const INNER: Record<Size, string> = {
${innerEntries},
};

export const ${entry.componentName} = forwardRef<SVGSVGElement, PolarisIconProps & { size?: Size }>(
  ({ size = ${entry.defaultSize}, ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox={\`0 0 \${size} \${size}\`}
      fill="none"
      aria-hidden={props['aria-label'] ? undefined : true}
      {...props}
      dangerouslySetInnerHTML={{ __html: INNER[size] }}
    />
  )
);
${entry.componentName}.displayName = '${entry.componentName}';
`;
}

function emitTypesFile(): string {
  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:icons\`.
import type { SVGAttributes } from 'react';

/** Sizes the polaris icon set ships at. Each icon picks a default size
 *  (24 if available, otherwise 18 or 32) — pass \`size\` to override.
 *  See \`packages/ui/scripts/build-icons.ts\`. */
export type IconSize = 18 | 24 | 32;

/** Common props for every \`@polaris/ui/icons\` component.
 *
 * Inherits all standard SVG attributes (\`className\`, \`onClick\`,
 * \`aria-label\`, etc.). \`color\` flows through via \`currentColor\` —
 * the design-team default stroke (#454C53) is replaced at build time,
 * so \`text-{token}\` Tailwind classes recolor monochrome icons. The
 * error icon's red is intentionally preserved (semantic).
 *
 * \`dangerouslySetInnerHTML\` and \`children\` are excluded because the
 * SVG body is generated at build time from the design source. */
export interface PolarisIconProps
  extends Omit<SVGAttributes<SVGSVGElement>, 'dangerouslySetInnerHTML' | 'children'> {
  /** Override the rendered size in pixels. Each icon allows the sizes
   *  it ships at (typically 18 / 24 / 32). */
  size?: IconSize;
}
`;
}

function emitIndex(entries: IconEntry[]): string {
  const lines = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => `export { ${e.componentName} } from './${e.slug}';`);
  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:icons\`.
//
// Polaris design icon set — ${entries.length} icons.
// Each component renders at 18 / 24 / 32 px (per design source). Pass
// \`size\` to pick; pass \`className\` to recolor via Tailwind.
//
//   import { ArrowDownIcon } from '@polaris/ui/icons';
//   <ArrowDownIcon size={18} className="text-label-neutral" />

export type { PolarisIconProps, IconSize } from './types';

${lines.join('\n')}
`;
}

function emitManifest(entries: IconEntry[]): string {
  const data = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => ({
      slug: e.slug,
      component: e.componentName,
      sizes: SIZES.filter((s) => e.inner[s] !== undefined),
      defaultSize: e.defaultSize,
    }));
  return JSON.stringify(data, null, 2) + '\n';
}

function main() {
  // Collect unique slugs across all sizes
  const slugs = new Set<string>();
  for (const size of SIZES) {
    const dir = join(ASSET_ROOT, String(size));
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (!entry.endsWith('.svg')) continue;
      slugs.add(entry.replace(/\.svg$/, ''));
    }
  }

  // Build entry objects
  const iconEntries: IconEntry[] = [];
  for (const slug of slugs) {
    iconEntries.push(buildEntry(slug));
  }

  // Recreate output dir
  rmSync(OUT_ROOT, { recursive: true, force: true });
  mkdirSync(OUT_ROOT, { recursive: true });

  // Emit types.ts (shared)
  writeFileSync(join(OUT_ROOT, 'types.ts'), emitTypesFile());

  // Emit one .tsx per icon
  for (const entry of iconEntries) {
    writeFileSync(join(OUT_ROOT, `${entry.slug}.tsx`), emitIconComponent(entry));
  }

  // Emit index + manifest
  writeFileSync(join(OUT_ROOT, 'index.ts'), emitIndex(iconEntries));
  writeFileSync(join(OUT_ROOT, 'MANIFEST.json'), emitManifest(iconEntries));

  console.log(
    `✓ wrote ${iconEntries.length} icon components → packages/ui/src/icons/`
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
