/**
 * build-file-icons — generates React file-type icon components from
 * `assets/svg/file-icons/32/`.
 *
 * The design-team file icons are multi-color (gradients, accent shapes),
 * unlike the monochrome UI icons. We preserve every color exactly and
 * render at a base 32×32, scaling via `width`/`height` props for other
 * sizes.
 *
 *   import { DocxIcon, FolderIcon } from '@polaris/ui/file-icons';
 *   <DocxIcon size={48} />
 *
 * Output: `packages/ui/src/file-icons/{slug}.tsx` + `index.ts` +
 * `MANIFEST.json`. Auto-generated; do not edit by hand. Run
 * `pnpm build:file-icons` to refresh.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ASSET_ROOT = resolve(__dirname, '../../../assets/svg/file-icons/32');
const OUT_ROOT = resolve(__dirname, '../src/file-icons');

interface FileIconEntry {
  slug: string;
  pascal: string;
  componentName: string;
  inner: string;
}

function pascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function extractInner(svg: string): string {
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error('SVG missing root <svg> tag');
  return m[1].trim();
}

function emitFileIconComponent(entry: FileIconEntry): string {
  const escaped = entry.inner.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
  return `// AUTO-GENERATED by packages/ui/scripts/build-file-icons.ts — do not edit by hand.
// Source: assets/svg/file-icons/32/${entry.slug}.svg
import { forwardRef } from 'react';
import type { FileIconProps } from './types';

const INNER = \`${escaped}\`;

export const ${entry.componentName} = forwardRef<SVGSVGElement, FileIconProps>(
  ({ size = 32, ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 0 32 32"
      fill="none"
      aria-hidden={props['aria-label'] ? undefined : true}
      {...props}
      dangerouslySetInnerHTML={{ __html: INNER }}
    />
  )
);
${entry.componentName}.displayName = '${entry.componentName}';
`;
}

function emitTypesFile(slugs: string[]): string {
  const literalUnion = slugs
    .sort()
    .map((s) => `'${s}'`)
    .join(' | ');
  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:file-icons\`.
import type { SVGAttributes } from 'react';

/** Every file type the icon set ships. Add new file types by dropping
 *  an SVG into \`assets/svg/file-icons/32/\` and re-running the build. */
export type FileIconType = ${literalUnion};

/** Common props for \`@polaris/ui/file-icons\` components.
 *
 * All file icons render at base 32×32 (the design master). Pass \`size\`
 * (in px) to scale uniformly. Colors are baked in per the design — file
 * icons are multi-color and \`text-\`/\`color\` props don't affect them.
 *
 * \`dangerouslySetInnerHTML\` and \`children\` are excluded because the
 * SVG body is generated at build time. */
export interface FileIconProps
  extends Omit<SVGAttributes<SVGSVGElement>, 'dangerouslySetInnerHTML' | 'children'> {
  /** Pixel size; default 32. Scales the entire icon uniformly. */
  size?: number;
}
`;
}

function emitIndex(entries: FileIconEntry[]): string {
  const exports = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => `export { ${e.componentName} } from './${e.slug}';`)
    .join('\n');

  // Lookup map: type slug → component (for the FileIcon dispatcher)
  const lookupEntries = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => `  '${e.slug}': ${e.componentName}`)
    .join(',\n');
  const importList = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => `import { ${e.componentName} } from './${e.slug}';`)
    .join('\n');

  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:file-icons\`.
//
// Polaris file-type icon set — ${entries.length} icons.
//
//   import { DocxIcon, FolderIcon } from '@polaris/ui/file-icons';
//   <DocxIcon size={48} />
//
// Or use the dispatcher (\`@polaris/ui/components/FileIcon\`):
//   import { FileIcon } from '@polaris/ui';
//   <FileIcon type="docx" size={48} />

export type { FileIconProps, FileIconType } from './types';

${exports}

${importList}

/** Map from file-type slug → React component. Used by the
 *  \`<FileIcon type="…" />\` dispatcher in \`@polaris/ui\`. */
export const FILE_ICON_REGISTRY = {
${lookupEntries},
} as const;
`;
}

function emitManifest(entries: FileIconEntry[]): string {
  const data = entries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((e) => ({ slug: e.slug, component: e.componentName }));
  return JSON.stringify(data, null, 2) + '\n';
}

function main() {
  const entries: FileIconEntry[] = [];
  for (const file of readdirSync(ASSET_ROOT)) {
    if (!file.endsWith('.svg')) continue;
    const slug = file.replace(/\.svg$/, '');
    const pascal = pascalCase(slug);
    entries.push({
      slug,
      pascal,
      componentName: `${pascal}Icon`,
      inner: extractInner(readFileSync(join(ASSET_ROOT, file), 'utf8')),
    });
  }

  // Idempotent + concurrency-safe — see build-ribbon-icons.ts for rationale.
  mkdirSync(OUT_ROOT, { recursive: true });

  const expected = new Set([
    'types.ts',
    'index.ts',
    'MANIFEST.json',
    ...entries.map((e) => `${e.slug}.tsx`),
  ]);

  writeFileSync(join(OUT_ROOT, 'types.ts'), emitTypesFile(entries.map((e) => e.slug)));
  for (const entry of entries) {
    writeFileSync(join(OUT_ROOT, `${entry.slug}.tsx`), emitFileIconComponent(entry));
  }
  writeFileSync(join(OUT_ROOT, 'index.ts'), emitIndex(entries));
  writeFileSync(join(OUT_ROOT, 'MANIFEST.json'), emitManifest(entries));

  pruneOrphans(OUT_ROOT, expected);

  console.log(`✓ wrote ${entries.length} file-icon components → packages/ui/src/file-icons/`);
}

/** Best-effort orphan removal for files in `dir` not in `expected`.
 *  Tolerates races with parallel generator invocations. */
function pruneOrphans(dir: string, expected: Set<string>): void {
  try {
    for (const f of readdirSync(dir)) {
      if (expected.has(f)) continue;
      try { unlinkSync(join(dir, f)); } catch { /* parallel run already pruned */ }
    }
  } catch { /* dir vanished mid-prune — next run repairs */ }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
