/**
 * Token generator — single source of truth is `src/tokens/*.ts`.
 *
 * This script reads those token modules and writes:
 *   src/styles/tokens.css    — CSS custom properties (light + dark)
 *
 * Usage:
 *   pnpm --filter @polaris/ui build:tokens     # regenerate
 *   pnpm --filter @polaris/ui build            # build runs this automatically
 *
 * CI verifies that the committed `tokens.css` matches what this script
 * would produce — see `.github/workflows/ci.yml` (`Verify token sync`).
 *
 * Run with `tsx` so we can import `.ts` modules directly without a
 * separate build step.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  brandPalette,
  brand,
  fileType,
  status,
  neutral,
  surface,
  text,
  radius,
  shadow,
  fontFamily,
  type ColorPair,
} from '../src/tokens';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, '../src/styles/tokens.css');

const HEADER = `/* Polaris Design Tokens — CSS Custom Properties
 *
 * AUTO-GENERATED by packages/ui/scripts/build-tokens.ts.
 * Do not edit this file by hand — change the source modules in
 * \`src/tokens/*.ts\` and run \`pnpm --filter @polaris/ui build:tokens\`.
 *
 * Theme switching: set \`data-theme="dark"\` on \`<html>\` or any ancestor.
 */
`;

const camelToKebab = (s: string) => s.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());

type ColorGroup = Record<string, ColorPair>;

/** Color groups + their CSS variable prefix. Empty prefix means the
 *  variable is named after the key directly (e.g. brandPalette.blue
 *  becomes --polaris-blue). */
const COLOR_GROUPS: Array<{ prefix: string; group: ColorGroup }> = [
  { prefix: '', group: brandPalette },
  { prefix: 'brand', group: brand },
  { prefix: 'file', group: fileType },
  { prefix: 'status', group: status },
  { prefix: 'neutral', group: neutral },
  { prefix: 'surface', group: surface },
  { prefix: 'text', group: text },
];

function emitColorBlock(mode: 'light' | 'dark'): string {
  const lines: string[] = [];
  for (const { prefix, group } of COLOR_GROUPS) {
    for (const [key, pair] of Object.entries(group)) {
      const cssKey = camelToKebab(key);
      const name = `--polaris${prefix ? `-${prefix}` : ''}-${cssKey}`;
      lines.push(`  ${name}: ${pair[mode]};`);
    }
  }
  return lines.join('\n');
}

function emitRadiusBlock(): string {
  // Radius is mode-independent.
  return Object.entries(radius)
    .map(([key, value]) => `  --polaris-radius-${camelToKebab(key)}: ${value};`)
    .join('\n');
}

function emitFontFamilyBlock(): string {
  // Font families are mode-independent. Tailwind preset's `font-polaris`
  // / `font-polaris-mono` utilities and demo/template globals.css both
  // reference these variables — must be emitted or font-family becomes
  // invalid across the app.
  return Object.entries(fontFamily)
    .map(([key, value]) => `  --polaris-font-${camelToKebab(key)}: ${value};`)
    .join('\n');
}

function emitShadowBlock(mode: 'light' | 'dark'): string {
  return Object.entries(shadow[mode])
    .map(([key, value]) => `  --polaris-shadow-${key}: ${value};`)
    .join('\n');
}

const lightBlock = `:root,
[data-theme="light"] {
${emitColorBlock('light')}

${emitRadiusBlock()}

${emitFontFamilyBlock()}

${emitShadowBlock('light')}
}`;

const darkBlock = `[data-theme="dark"] {
${emitColorBlock('dark')}

${emitShadowBlock('dark')}
}`;

const css = `${HEADER}\n${lightBlock}\n\n${darkBlock}\n`;

writeFileSync(OUTPUT, css);
console.log(`✓ wrote ${OUTPUT.replace(process.cwd() + '/', '')}`);
