/**
 * Token generator — single source of truth is `src/tokens/*.ts`.
 *
 * This script reads those token modules and writes:
 *   src/styles/tokens.css    — CSS custom properties (light + dark)
 *
 * Usage:
 *   pnpm --filter @polaris/ui build:tokens     # regenerate
 *   pnpm --filter @polaris/ui build            # build runs this automatically
 *
 * CI verifies that the committed `tokens.css` matches what this script
 * would produce — see `.github/workflows/ci.yml` (`Verify token sync`).
 *
 * Run with `tsx` so we can import `.ts` modules directly without a
 * separate build step.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  brandPalette,
  brand,
  fileType,
  status,
  neutral,
  surface,
  text,
  radius,
  shadow,
  fontFamily,
  bluePalette,
  darkBluePalette,
  greenPalette,
  orangePalette,
  redPalette,
  purplePalette,
  skyBluePalette,
  blueSupplementaryPalette,
  violetPalette,
  cyanPalette,
  yellowPalette,
  grayRamp,
  label,
  background,
  layer,
  interaction,
  fill,
  line,
  accentBrand,
  accentAction,
  focus,
  staticColors,
  state,
  primary,
  ai,
  type ColorPair,
} from '../src/tokens';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, '../src/styles/tokens.css');

const HEADER = `/* Polaris Design Tokens — CSS Custom Properties
 *
 * AUTO-GENERATED by packages/ui/scripts/build-tokens.ts.
 * Do not edit this file by hand — change the source modules in
 * \`src/tokens/*.ts\` and run \`pnpm --filter @polaris/ui build:tokens\`.
 *
 * Theme switching: set \`data-theme="dark"\` on \`<html>\` or any ancestor.
 */
`;

const camelToKebab = (s: string) => s.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());

type ColorGroup = Record<string, ColorPair>;

/** Color groups + their CSS variable prefix. Empty prefix means the
 *  variable is named after the key directly (e.g. brandPalette.blue
 *  becomes --polaris-blue). */
const COLOR_GROUPS: Array<{ prefix: string; group: ColorGroup }> = [
  // v0.6 groups (kept for backward compat — `surface.canvas` etc.)
  { prefix: '',         group: brandPalette },
  { prefix: 'brand',    group: brand },
  { prefix: 'file',     group: fileType },
  { prefix: 'status',   group: status },
  { prefix: 'neutral',  group: neutral },
  { prefix: 'surface',  group: surface },
  { prefix: 'text',     group: text },
  // v1 spec semantic tokens (v0.7-rc.1 expanded)
  { prefix: 'label',         group: label },
  { prefix: 'background',    group: background },
  { prefix: 'layer',         group: layer },
  { prefix: 'interaction',   group: interaction },
  { prefix: 'fill',          group: fill },
  { prefix: 'line',          group: line },
  { prefix: 'accent-brand',  group: accentBrand },
  { prefix: 'accent-action', group: accentAction },
  { prefix: 'focus',         group: focus },
  { prefix: 'static',        group: staticColors },
  { prefix: 'state',         group: state },
  // legacy / Polaris-specific aliases (still emitted as CSS vars)
  { prefix: 'primary',       group: primary },
  { prefix: 'ai',            group: ai },
];

function emitColorBlock(mode: 'light' | 'dark'): string {
  const lines: string[] = [];
  for (const { prefix, group } of COLOR_GROUPS) {
    for (const [key, pair] of Object.entries(group)) {
      const cssKey = camelToKebab(key);
      const name = `--polaris${prefix ? `-${prefix}` : ''}-${cssKey}`;
      lines.push(`  ${name}: ${pair[mode]};`);
    }
  }
  return lines.join('\n');
}

/** Emit primitive ramps (light only — design team hasn't supplied a
 *  dark-mode ramp yet). Each step gets its own custom property:
 *  `--polaris-blue-50`, `--polaris-purple-30`, `--polaris-blue-90`, etc.
 *
 *  v0.7-rc.1: brand ramps gain step `90` (darkest) and an `05`
 *  leading-zero key matching the design sheet. The legacy `5` key is
 *  emitted as a deprecated CSS variable for backward compat. Five new
 *  supplementary families (Sky Blue, Blue, Violet, Cyan, Yellow) are
 *  added per the primitive palette reference.
 *
 *  `dark-blue` (BI / corporate) is also emitted now; previously it
 *  lived only in the TS export.
 */
function emitRampBlock(): string {
  const ramps: Array<[string, Record<string, string>]> = [
    // brand (5 colors + dark blue)
    ['blue',      bluePalette],
    ['dark-blue', darkBluePalette],
    ['green',     greenPalette],
    ['orange',    orangePalette],
    ['red',       redPalette],
    ['purple',    purplePalette],
    // supplementary (v0.7-rc.1) — charts, plan badges, file-type extensions
    ['sky-blue',         skyBluePalette],
    ['blue-supplementary', blueSupplementaryPalette],
    ['violet',           violetPalette],
    ['cyan',             cyanPalette],
    ['yellow',           yellowPalette],
    // ui backbone
    ['gray',             grayRamp],
  ];
  return ramps
    .flatMap(([name, ramp]) =>
      Object.entries(ramp).map(([step, hex]) => `  --polaris-${name}-${step}: ${hex};`)
    )
    .join('\n');
}

function emitRadiusBlock(): string {
  // Radius is mode-independent.
  return Object.entries(radius)
    .map(([key, value]) => `  --polaris-radius-${camelToKebab(key)}: ${value};`)
    .join('\n');
}

function emitFontFamilyBlock(): string {
  // Font families are mode-independent. Tailwind preset's `font-polaris`
  // / `font-polaris-mono` utilities and demo/template globals.css both
  // reference these variables — must be emitted or font-family becomes
  // invalid across the app.
  return Object.entries(fontFamily)
    .map(([key, value]) => `  --polaris-font-${camelToKebab(key)}: ${value};`)
    .join('\n');
}

function emitShadowBlock(mode: 'light' | 'dark'): string {
  return Object.entries(shadow[mode])
    .map(([key, value]) => `  --polaris-shadow-${key}: ${value};`)
    .join('\n');
}

const lightBlock = `:root,
[data-theme="light"] {
${emitColorBlock('light')}

${emitRampBlock()}

${emitRadiusBlock()}

${emitFontFamilyBlock()}

${emitShadowBlock('light')}
}`;

const darkBlock = `[data-theme="dark"] {
${emitColorBlock('dark')}

${emitShadowBlock('dark')}
}`;

/* v0.7-rc.1 — mobile type scale per DESIGN.md §3. Each type level
 * shifts down one step on viewports ≤ 767px. The override targets
 * Tailwind utility classes generated from the preset's `fontSize`
 * map, so consumers using `text-polaris-display` etc. get the smaller
 * sizes automatically without writing media queries themselves.
 *
 * Body3 / Caption1 / Caption2 stay unchanged on mobile per spec. */
const mobileTypographyBlock = `@media (max-width: 767px) {
  .text-polaris-display  { font-size: 32px; line-height: 44px; }
  .text-polaris-title    { font-size: 28px; line-height: 40px; }
  .text-polaris-heading1 { font-size: 24px; line-height: 34px; }
  .text-polaris-heading2 { font-size: 20px; line-height: 28px; }
  .text-polaris-heading3 { font-size: 18px; line-height: 26px; }
  .text-polaris-heading4 { font-size: 16px; line-height: 24px; }
  .text-polaris-body1    { font-size: 14px; line-height: 21px; }
  .text-polaris-body2    { font-size: 13px; line-height: 20px; }
  /* Body3 (13), Caption1 (12), Caption2 (11) — unchanged */
}`;

const css = `${HEADER}\n${lightBlock}\n\n${darkBlock}\n\n${mobileTypographyBlock}\n`;

writeFileSync(OUTPUT, css);
console.log(`✓ wrote ${OUTPUT.replace(process.cwd() + '/', '')}`);
