/**
 * build-logos — generates React logo components from
 * `assets/svg/logos/{polaris-office,nova}/*.svg`.
 *
 * Outputs two components:
 *
 *   <PolarisLogo variant="horizontal" />            (horizontal lockup)
 *   <PolarisLogo variant="horizontal" tone="negative" />
 *   <PolarisLogo variant="symbol" size={144} />     (square symbol)
 *   <PolarisLogo variant="favicon" size={32} />     (small icon)
 *
 *   <NovaLogo />                  (default purple)
 *   <NovaLogo tone="white" />     (negative for dark surfaces)
 *
 * Logo SVGs are multi-path with brand colors baked in — we don't try
 * to recolor them. `width`/`height` props scale uniformly while
 * preserving aspect ratio (each variant has its own intrinsic size).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { prefixSvgIds } from './_svg-utils';

const __dirname = dirname(fileURLToPath(import.meta.url));
const POLARIS_ROOT = resolve(__dirname, '../../../assets/svg/logos/polaris-office');
const NOVA_ROOT = resolve(__dirname, '../../../assets/svg/logos/nova');
const OUT_ROOT = resolve(__dirname, '../src/logos');

interface SvgInfo {
  inner: string;
  viewBox: string;
  intrinsicWidth: number;
  intrinsicHeight: number;
}

function parseSvg(svg: string): SvgInfo {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 0 0';
  const widthAttr = parseFloat(svg.match(/width="([\d.]+)"/)?.[1] ?? '0');
  const heightAttr = parseFloat(svg.match(/height="([\d.]+)"/)?.[1] ?? '0');
  const inner = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1].trim() ?? '';
  return {
    inner,
    viewBox,
    intrinsicWidth: widthAttr || parseFloat(viewBox.split(' ')[2]) || 0,
    intrinsicHeight: heightAttr || parseFloat(viewBox.split(' ')[3]) || 0,
  };
}

function escape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
}

function emitPolaris(): string {
  // Prefix internal ids per-variant — see build-ribbon-icons.ts. The four
  // variants share the same Figma export pipeline so identical numeric
  // ids are very likely; without prefixing, two variants on the same
  // page would step on each other's gradients/clips.
  const horizontal = parseSvg(readFileSync(join(POLARIS_ROOT, 'horizontal.svg'), 'utf8'));
  horizontal.inner = prefixSvgIds(horizontal.inner, 'polaris-horizontal');
  const horizontalNeg = parseSvg(readFileSync(join(POLARIS_ROOT, 'horizontal-negative.svg'), 'utf8'));
  horizontalNeg.inner = prefixSvgIds(horizontalNeg.inner, 'polaris-horizontal-neg');
  const symbol = parseSvg(readFileSync(join(POLARIS_ROOT, 'symbol-144.svg'), 'utf8'));
  symbol.inner = prefixSvgIds(symbol.inner, 'polaris-symbol');
  const favicon = parseSvg(readFileSync(join(POLARIS_ROOT, 'favicon.svg'), 'utf8'));
  favicon.inner = prefixSvgIds(favicon.inner, 'polaris-favicon');

  return `// AUTO-GENERATED by packages/ui/scripts/build-logos.ts — do not edit by hand.
import { forwardRef } from 'react';
import type { LogoBaseProps } from './types';

/**
 * Polaris Office logo lockup variants.
 *
 *   horizontal           — wordmark + symbol, primary placement
 *   horizontal-negative  — same, designed for dark backgrounds
 *   symbol               — square brand mark, no wordmark
 *   favicon              — minimal mark for small renderings (≤32px)
 */
export type PolarisLogoVariant = 'horizontal' | 'symbol' | 'favicon';

export interface PolarisLogoProps extends LogoBaseProps {
  variant?: PolarisLogoVariant;
  /** Use the inverted "negative" color treatment. Only applies to the
   *  \`horizontal\` variant; the symbol/favicon stay full-color. */
  tone?: 'default' | 'negative';
}

const HORIZONTAL_INNER = \`${escape(horizontal.inner)}\`;
const HORIZONTAL_NEG_INNER = \`${escape(horizontalNeg.inner)}\`;
const SYMBOL_INNER = \`${escape(symbol.inner)}\`;
const FAVICON_INNER = \`${escape(favicon.inner)}\`;

const VARIANT_DATA = {
  horizontal: { viewBox: '${horizontal.viewBox}', w: ${horizontal.intrinsicWidth}, h: ${horizontal.intrinsicHeight}, inner: HORIZONTAL_INNER, innerNeg: HORIZONTAL_NEG_INNER },
  symbol:     { viewBox: '${symbol.viewBox}',     w: ${symbol.intrinsicWidth}, h: ${symbol.intrinsicHeight}, inner: SYMBOL_INNER,     innerNeg: SYMBOL_INNER     },
  favicon:    { viewBox: '${favicon.viewBox}',    w: ${favicon.intrinsicWidth}, h: ${favicon.intrinsicHeight}, inner: FAVICON_INNER,    innerNeg: FAVICON_INNER    },
} as const;

export const PolarisLogo = forwardRef<SVGSVGElement, PolarisLogoProps>(
  ({ variant = 'horizontal', tone = 'default', size, height, width, ...props }, ref) => {
    const data = VARIANT_DATA[variant];
    const inner = tone === 'negative' ? data.innerNeg : data.inner;
    // Scale: pass \`size\` to set height in px (width derived from
    // intrinsic ratio). Or pass \`width\`/\`height\` directly.
    const aspect = data.w / data.h;
    const finalHeight = height ?? size ?? data.h;
    const finalWidth =
      width ??
      (size !== undefined
        ? Math.round(Number(size) * aspect)
        : data.w);
    return (
      <svg
        ref={ref}
        width={finalWidth}
        height={finalHeight}
        viewBox={data.viewBox}
        fill="none"
        role="img"
        aria-label={props['aria-label'] ?? 'Polaris Office'}
        {...props}
        dangerouslySetInnerHTML={{ __html: inner }}
      />
    );
  }
);
PolarisLogo.displayName = 'PolarisLogo';
`;
}

function emitNova(): string {
  const original = parseSvg(readFileSync(join(NOVA_ROOT, 'original.svg'), 'utf8'));
  original.inner = prefixSvgIds(original.inner, 'nova-original');
  const white = parseSvg(readFileSync(join(NOVA_ROOT, 'white.svg'), 'utf8'));
  white.inner = prefixSvgIds(white.inner, 'nova-white');

  return `// AUTO-GENERATED by packages/ui/scripts/build-logos.ts — do not edit by hand.
import { forwardRef } from 'react';
import type { LogoBaseProps } from './types';

/** Nova (AI feature) logo. \`default\` is the brand purple; \`white\`
 *  is the inverted treatment for dark / colored surfaces. */
export interface NovaLogoProps extends LogoBaseProps {
  tone?: 'default' | 'white';
}

const ORIGINAL_INNER = \`${escape(original.inner)}\`;
const WHITE_INNER = \`${escape(white.inner)}\`;

const VIEW_BOX = '${original.viewBox}';
const INTRINSIC_W = ${original.intrinsicWidth};
const INTRINSIC_H = ${original.intrinsicHeight};

export const NovaLogo = forwardRef<SVGSVGElement, NovaLogoProps>(
  ({ tone = 'default', size, height, width, ...props }, ref) => {
    const inner = tone === 'white' ? WHITE_INNER : ORIGINAL_INNER;
    const aspect = INTRINSIC_W / INTRINSIC_H;
    const finalHeight = height ?? size ?? INTRINSIC_H;
    const finalWidth =
      width ??
      (size !== undefined ? Math.round(Number(size) * aspect) : INTRINSIC_W);
    return (
      <svg
        ref={ref}
        width={finalWidth}
        height={finalHeight}
        viewBox={VIEW_BOX}
        fill="none"
        role="img"
        aria-label={props['aria-label'] ?? 'Nova'}
        {...props}
        dangerouslySetInnerHTML={{ __html: inner }}
      />
    );
  }
);
NovaLogo.displayName = 'NovaLogo';
`;
}

function emitTypes(): string {
  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:logos\`.
import type { SVGAttributes } from 'react';

/** Shared base props for logo components. Logos have brand colors
 *  baked in — \`color\` / \`text-{token}\` does not recolor them; pick
 *  a different \`tone\` instead.
 *
 *  \`size\` sets the rendered height in px; width is derived from the
 *  intrinsic aspect ratio. Override \`width\` and/or \`height\`
 *  explicitly for non-uniform scaling. */
export interface LogoBaseProps
  extends Omit<SVGAttributes<SVGSVGElement>, 'dangerouslySetInnerHTML' | 'children' | 'width' | 'height'> {
  /** Render at this height (px). Width auto-computed to keep aspect. */
  size?: number;
  /** Override width directly (px). Combine with \`height\` for non-uniform scaling. */
  width?: number;
  /** Override height directly (px). */
  height?: number;
}
`;
}

function emitIndex(): string {
  return `// AUTO-GENERATED — do not edit. Run \`pnpm build:logos\`.
//
//   import { PolarisLogo, NovaLogo } from '@polaris/ui/logos';
//   <PolarisLogo variant="horizontal" size={32} />
//   <NovaLogo tone="white" />

export type { LogoBaseProps } from './types';
export { PolarisLogo, type PolarisLogoProps, type PolarisLogoVariant } from './polaris';
export { NovaLogo, type NovaLogoProps } from './nova';
`;
}

function main() {
  // Idempotent + concurrency-safe — see build-ribbon-icons.ts for rationale.
  mkdirSync(OUT_ROOT, { recursive: true });

  const expected = new Set(['types.ts', 'polaris.tsx', 'nova.tsx', 'index.ts']);

  writeFileSync(join(OUT_ROOT, 'types.ts'), emitTypes());
  writeFileSync(join(OUT_ROOT, 'polaris.tsx'), emitPolaris());
  writeFileSync(join(OUT_ROOT, 'nova.tsx'), emitNova());
  writeFileSync(join(OUT_ROOT, 'index.ts'), emitIndex());

  pruneOrphans(OUT_ROOT, expected);

  console.log('✓ wrote PolarisLogo + NovaLogo → packages/ui/src/logos/');
}

/** Best-effort orphan removal for files in `dir` not in `expected`.
 *  Tolerates races with parallel generator invocations. */
function pruneOrphans(dir: string, expected: Set<string>): void {
  try {
    for (const f of readdirSync(dir)) {
      if (expected.has(f)) continue;
      try { unlinkSync(join(dir, f)); } catch { /* parallel run already pruned */ }
    }
  } catch { /* dir vanished mid-prune — next run repairs */ }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
